import type { ExerciseSeed } from "./types";

// One practice exercise per topic in src/content/grammar-topics.ts (matched
// via the `topic` slug), with questions ordered from easier to harder.

export const grammarExercises: ExerciseSeed[] = [
  {
    slug: "grammar-advanced-tenses",
    type: "GRAMMAR_DRILL",
    skill: "GRAMMAR",
    level: "B2",
    title: "Advanced tenses practice",
    topic: "advanced-tenses",
    instructions: "Choose the option that best completes each sentence.",
    content: {},
    questions: [
      {
        order: 1,
        questionType: "MULTIPLE_CHOICE",
        prompt: "I ___ this book twice already, so I'll lend it to you.",
        options: ["A) read", "B) have read", "C) was reading", "D) had read"],
        correctAnswer: "B) have read",
        explanation: "Present perfect for a completed action with present relevance (I can lend it now).",
        distractorExplanations: {
          "A) read": "Simple past needs a specific past time reference, which is missing here.",
          "C) was reading": "Past continuous suggests an interrupted action, not a completed one.",
          "D) had read": "Past perfect would need a second past reference point to relate to.",
        },
        grammarCategory: "TENSES",
      },
      {
        order: 2,
        questionType: "MULTIPLE_CHOICE",
        prompt: "She ___ for the company for six years when it was sold.",
        options: ["A) worked", "B) has worked", "C) had been working", "D) was working"],
        correctAnswer: "C) had been working",
        explanation: "Past perfect continuous shows duration of an activity up to a point in the past ('when it was sold').",
        distractorExplanations: {
          "A) worked": "Doesn't capture the ongoing duration up to the past event.",
          "B) has worked": "Present perfect can't be used with a clearly past time frame like 'when it was sold'.",
          "D) was working": "Past continuous doesn't convey the six-year duration as clearly as the perfect continuous.",
        },
        grammarCategory: "TENSES",
      },
      {
        order: 3,
        questionType: "MULTIPLE_CHOICE",
        prompt: "By next April, they ___ married for ten years.",
        options: ["A) will be", "B) will have been", "C) are", "D) have been"],
        correctAnswer: "B) will have been",
        explanation: "Future perfect (continuous idea via 'have been') expresses a state that will be complete/ongoing by a future point.",
        distractorExplanations: {
          "A) will be": "Doesn't capture the sense of completion by a future deadline.",
          "C) are": "Present simple doesn't work with 'by next April' looking forward.",
          "D) have been": "Present perfect doesn't reach into the future as 'by next April' requires.",
        },
        grammarCategory: "TENSES",
      },
      {
        order: 4,
        questionType: "MULTIPLE_CHOICE",
        prompt: "I'm exhausted — I ___ boxes all afternoon.",
        options: ["A) have moved", "B) have been moving", "C) moved", "D) move"],
        correctAnswer: "B) have been moving",
        explanation: "Present perfect continuous emphasises the tiring, ongoing nature of the activity, matching 'I'm exhausted'.",
        distractorExplanations: {
          "A) have moved": "Present perfect simple focuses on completed result, not the tiring process.",
          "C) moved": "Simple past needs a specific finished time frame, not 'all afternoon' linked to now.",
          "D) move": "Present simple doesn't fit a specific recent activity at all.",
        },
        grammarCategory: "TENSES",
      },
      {
        order: 5,
        questionType: "MULTIPLE_CHOICE",
        prompt: "When I finally called her back, she ___ already ___ the office.",
        options: ["A) has / left", "B) had / left", "C) was / leaving", "D) did / leave"],
        correctAnswer: "B) had / left",
        explanation: "Past perfect ('had left') clearly places her departure before the past action of calling back.",
        distractorExplanations: {
          "A) has / left": "Present perfect doesn't work within a past narrative like this.",
          "C) was / leaving": "Past continuous would suggest an interrupted, incomplete action.",
          "D) did / leave": "Not a standard perfect structure; loses the 'before another past action' meaning.",
        },
        grammarCategory: "TENSES",
      },
    ],
  },
  {
    slug: "grammar-conditionals",
    type: "GRAMMAR_DRILL",
    skill: "GRAMMAR",
    level: "C1",
    title: "Conditionals and mixed conditionals practice",
    topic: "conditionals",
    instructions: "Choose the option that best completes each sentence.",
    content: {},
    questions: [
      {
        order: 1,
        questionType: "MULTIPLE_CHOICE",
        prompt: "If it ___ tomorrow, we'll cancel the picnic.",
        options: ["A) rains", "B) will rain", "C) rained", "D) would rain"],
        correctAnswer: "A) rains",
        explanation: "First conditional: if + present simple, ... will + base form.",
        distractorExplanations: {
          "B) will rain": "The 'if' clause never takes 'will' in a first conditional.",
          "C) rained": "Past simple belongs to the second conditional, not this real future situation.",
          "D) would rain": "'Would' doesn't go in the if-clause.",
        },
        grammarCategory: "CONDITIONALS",
      },
      {
        order: 2,
        questionType: "MULTIPLE_CHOICE",
        prompt: "If I ___ you, I wouldn't accept that offer.",
        options: ["A) am", "B) was", "C) were", "D) will be"],
        correctAnswer: "C) were",
        explanation: "Second conditional hypothetical: 'If I were you' uses subjunctive 'were' for all persons in formal/standard usage.",
        distractorExplanations: {
          "A) am": "Present simple doesn't fit a hypothetical second conditional.",
          "B) was": "Acceptable informally, but 'were' is the standard C1-level form in this fixed expression.",
          "D) will be": "'Will' never appears in the if-clause.",
        },
        grammarCategory: "CONDITIONALS",
      },
      {
        order: 3,
        questionType: "MULTIPLE_CHOICE",
        prompt: "If she ___ harder at school, she would have gone to university.",
        options: ["A) studied", "B) had studied", "C) studies", "D) would study"],
        correctAnswer: "B) had studied",
        explanation: "Third conditional: if + past perfect, ... would have + past participle, for an unreal past situation.",
        distractorExplanations: {
          "A) studied": "Past simple belongs to the second conditional, not a completed past hypothesis.",
          "C) studies": "Present simple doesn't fit a past hypothetical at all.",
          "D) would study": "'Would' doesn't go in the if-clause.",
        },
        grammarCategory: "CONDITIONALS",
      },
      {
        order: 4,
        questionType: "MULTIPLE_CHOICE",
        prompt: "If he had taken that promotion, he ___ so stressed right now.",
        options: ["A) would be", "B) would have been", "C) will be", "D) is"],
        correctAnswer: "A) would be",
        explanation: "Mixed conditional: past condition (had taken) + present result (would be) — 'right now' signals the present time frame.",
        distractorExplanations: {
          "B) would have been": "This would describe a past result, but 'right now' requires a present result.",
          "C) will be": "'Will' isn't used for hypothetical/unreal results.",
          "D) is": "Missing the conditional 'would' needed for a hypothetical result.",
        },
        grammarCategory: "CONDITIONALS",
      },
      {
        order: 5,
        questionType: "MULTIPLE_CHOICE",
        prompt: "If you weren't so disorganised, you ___ the deadline last week.",
        options: ["A) wouldn't miss", "B) wouldn't have missed", "C) don't miss", "D) hadn't missed"],
        correctAnswer: "B) wouldn't have missed",
        explanation: "Mixed conditional: general/present condition (weren't so disorganised) + past result (wouldn't have missed, 'last week').",
        distractorExplanations: {
          "A) wouldn't miss": "This describes a present/future result, but 'last week' requires a past result.",
          "C) don't miss": "Not a conditional form at all.",
          "D) hadn't missed": "This is a past perfect form, not the 'would have' needed for the result clause.",
        },
        grammarCategory: "CONDITIONALS",
      },
    ],
  },
  {
    slug: "grammar-modal-verbs",
    type: "GRAMMAR_DRILL",
    skill: "GRAMMAR",
    level: "C1",
    title: "Modal verbs, including modals in the past",
    topic: "modal-verbs",
    instructions: "Choose the option that best completes each sentence.",
    content: {},
    questions: [
      {
        order: 1,
        questionType: "MULTIPLE_CHOICE",
        prompt: "She's not answering her phone — she ___ be in a meeting.",
        options: ["A) must", "B) should", "C) can't", "D) needn't"],
        correctAnswer: "A) must",
        explanation: "'Must' expresses strong logical certainty about a present situation, fitting the deduction here.",
        distractorExplanations: {
          "B) should": "'Should' expresses expectation/advice, not confident deduction.",
          "C) can't": "'Can't' would express the opposite — near-certainty that something is NOT the case.",
          "D) needn't": "'Needn't' expresses lack of obligation, unrelated to this deduction.",
        },
        grammarCategory: "MODAL_VERBS",
      },
      {
        order: 2,
        questionType: "MULTIPLE_CHOICE",
        prompt: "You ___ have shouted at him — he was only trying to help.",
        options: ["A) mustn't", "B) shouldn't", "C) can't", "D) needn't"],
        correctAnswer: "B) shouldn't",
        explanation: "'Shouldn't have + past participle' criticises a past action that wasn't a good idea.",
        distractorExplanations: {
          "A) mustn't": "'Mustn't have' isn't a standard structure in English.",
          "C) can't": "'Can't have' expresses certainty something didn't happen, not criticism of an action that did.",
          "D) needn't": "'Needn't have' means the action wasn't necessary, not that it was wrong to do.",
        },
        grammarCategory: "MODAL_VERBS",
      },
      {
        order: 3,
        questionType: "MULTIPLE_CHOICE",
        prompt: "I ___ have printed those documents — they'd already been sent electronically.",
        options: ["A) shouldn't", "B) mustn't", "C) needn't", "D) can't"],
        correctAnswer: "C) needn't",
        explanation: "'Needn't have + past participle' means the action was done but turned out to be unnecessary.",
        distractorExplanations: {
          "A) shouldn't": "This would mean printing them was a bad/wrong decision, not just unnecessary.",
          "B) mustn't": "'Mustn't have' isn't a standard structure.",
          "D) can't": "'Can't have' expresses certainty something didn't happen — wrong meaning here.",
        },
        grammarCategory: "MODAL_VERBS",
      },
      {
        order: 4,
        questionType: "MULTIPLE_CHOICE",
        prompt: "There's no answer at the door — they ___ have gone out already.",
        options: ["A) might", "B) should", "C) needn't", "D) mustn't"],
        correctAnswer: "A) might",
        explanation: "'Might have' expresses a past possibility, appropriate uncertainty for this situation.",
        distractorExplanations: {
          "B) should": "'Should have' implies expectation/obligation, not simple possibility.",
          "C) needn't": "Doesn't fit — this isn't about necessity.",
          "D) mustn't": "'Mustn't have' isn't standard; also wrong meaning (prohibition, not possibility).",
        },
        grammarCategory: "MODAL_VERBS",
      },
      {
        order: 5,
        questionType: "MULTIPLE_CHOICE",
        prompt: "He speaks four languages fluently — he ___ have lived abroad for years.",
        options: ["A) could", "B) must", "C) needn't", "D) shouldn't"],
        correctAnswer: "B) must",
        explanation: "'Must have' expresses a confident deduction based on strong evidence (fluent in four languages).",
        distractorExplanations: {
          "A) could": "'Could have' suggests mere possibility, weaker than the confident deduction implied here.",
          "C) needn't": "Unrelated meaning — necessity, not deduction.",
          "D) shouldn't": "Would express criticism/unexpectedness, not a logical deduction.",
        },
        grammarCategory: "MODAL_VERBS",
      },
    ],
  },
  {
    slug: "grammar-passive-structures",
    type: "GRAMMAR_DRILL",
    skill: "GRAMMAR",
    level: "C1",
    title: "Passive structures practice",
    topic: "passive-structures",
    instructions: "Choose the option that best completes each sentence.",
    content: {},
    questions: [
      {
        order: 1,
        questionType: "MULTIPLE_CHOICE",
        prompt: "The new policy ___ next month.",
        options: ["A) will announce", "B) will be announced", "C) is announcing", "D) announces"],
        correctAnswer: "B) will be announced",
        explanation: "Passive needed since the policy doesn't announce itself — 'will be announced' by someone unspecified.",
        distractorExplanations: {
          "A) will announce": "Active voice would need a subject that performs the announcing.",
          "C) is announcing": "Active present continuous doesn't fit a future scheduled event with 'next month' this way, and is still active voice.",
          "D) announces": "Simple present active doesn't fit a specific future scheduled action.",
        },
        grammarCategory: "PASSIVE_VOICE",
      },
      {
        order: 2,
        questionType: "MULTIPLE_CHOICE",
        prompt: "It ___ that remote work increases productivity for most employees.",
        options: ["A) is believed", "B) believes", "C) is believing", "D) believed"],
        correctAnswer: "A) is believed",
        explanation: "'It is believed that...' is the standard impersonal passive reporting structure.",
        distractorExplanations: {
          "B) believes": "Active voice needs a specific subject who believes — 'It believes' doesn't make sense here.",
          "C) is believing": "'Believe' is a stative verb, not normally used in the continuous form.",
          "D) believed": "Missing the auxiliary 'is' needed for the passive.",
        },
        grammarCategory: "PASSIVE_VOICE",
      },
      {
        order: 3,
        questionType: "MULTIPLE_CHOICE",
        prompt: "The bridge ___ by the time the festival starts.",
        options: ["A) will finish", "B) will have been finished", "C) finishes", "D) is finished"],
        correctAnswer: "B) will have been finished",
        explanation: "Future perfect passive: an action completed by a future point in time, performed on the subject (the bridge).",
        distractorExplanations: {
          "A) will finish": "Active voice would need the bridge to perform the finishing, which doesn't make sense.",
          "C) finishes": "Simple present doesn't express a future deadline.",
          "D) is finished": "Present simple passive doesn't capture the 'by the time' future deadline.",
        },
        grammarCategory: "PASSIVE_VOICE",
      },
      {
        order: 4,
        questionType: "MULTIPLE_CHOICE",
        prompt: "The CEO ___ to have known about the fraud for months.",
        options: ["A) says", "B) is said", "C) said", "D) is saying"],
        correctAnswer: "B) is said",
        explanation: "'Someone is said to have done something' is a passive reporting structure distancing the writer from the claim.",
        distractorExplanations: {
          "A) says": "Active voice would need a different subject making the claim about the CEO, not the CEO as subject here.",
          "C) said": "Missing the auxiliary 'is' for the passive present structure.",
          "D) is saying": "Wrong — this would mean the CEO is actively saying something, not that something is said about them.",
        },
        grammarCategory: "PASSIVE_VOICE",
      },
      {
        order: 5,
        questionType: "MULTIPLE_CHOICE",
        prompt: "This wine ___ from grapes grown in the same valley for over a century.",
        options: ["A) makes", "B) is made", "C) made", "D) is making"],
        correctAnswer: "B) is made",
        explanation: "Passive present simple describes a general/factual process — the wine doesn't make itself.",
        distractorExplanations: {
          "A) makes": "Active voice needs a subject performing the making, which 'this wine' doesn't.",
          "C) made": "Missing the auxiliary 'is' for present passive.",
          "D) is making": "Wrong voice/aspect — implies the wine is actively making something.",
        },
        grammarCategory: "PASSIVE_VOICE",
      },
    ],
  },
  {
    slug: "grammar-reported-speech",
    type: "GRAMMAR_DRILL",
    skill: "GRAMMAR",
    level: "B2",
    title: "Reported speech practice",
    topic: "reported-speech",
    instructions: "Choose the option that best completes each sentence.",
    content: {},
    questions: [
      {
        order: 1,
        questionType: "MULTIPLE_CHOICE",
        prompt: "\"I'll finish it tomorrow,\" she said. → She said she ___ it the next day.",
        options: ["A) will finish", "B) would finish", "C) finishes", "D) had finished"],
        correctAnswer: "B) would finish",
        explanation: "'Will' backshifts to 'would' when the reporting verb is in the past.",
        distractorExplanations: {
          "A) will finish": "'Will' should backshift to 'would' after a past reporting verb.",
          "C) finishes": "Loses the future meaning of the original statement entirely.",
          "D) had finished": "Past perfect would suggest the action was already completed, changing the meaning.",
        },
        grammarCategory: "REPORTED_SPEECH",
      },
      {
        order: 2,
        questionType: "MULTIPLE_CHOICE",
        prompt: "\"I forgot to lock the door,\" he admitted. → He admitted ___ to lock the door.",
        options: ["A) forgetting", "B) to forget", "C) forgot", "D) he forgets"],
        correctAnswer: "A) forgetting",
        explanation: "'Admit' is followed by a gerund (admit doing something), reporting a past action.",
        distractorExplanations: {
          "B) to forget": "'Admit' is not followed by a to-infinitive.",
          "C) forgot": "Not a grammatical pattern after 'admitted' without a conjunction.",
          "D) he forgets": "Would need 'that' and doesn't match the required pattern with 'admitted'.",
        },
        grammarCategory: "REPORTED_SPEECH",
      },
      {
        order: 3,
        questionType: "MULTIPLE_CHOICE",
        prompt: "\"Don't touch that wire!\" she warned him. → She warned him ___ touch the wire.",
        options: ["A) don't", "B) not to", "C) to not", "D) didn't"],
        correctAnswer: "B) not to",
        explanation: "Negative reported imperatives use 'warn/tell someone not to do something'.",
        distractorExplanations: {
          "A) don't": "Direct imperative form isn't used inside reported speech like this.",
          "C) to not": "Non-standard word order; 'not to' is the correct standard form.",
          "D) didn't": "Doesn't fit the infinitive structure required after 'warned him'.",
        },
        grammarCategory: "REPORTED_SPEECH",
      },
      {
        order: 4,
        questionType: "MULTIPLE_CHOICE",
        prompt: "\"Why don't we ask a lawyer?\" he said. → He ___ asking a lawyer.",
        options: ["A) suggested", "B) told", "C) said", "D) asked"],
        correctAnswer: "A) suggested",
        explanation: "'Suggest doing something' precisely reports the meaning of 'Why don't we...?' as a suggestion.",
        distractorExplanations: {
          "B) told": "'Told' needs an object and an infinitive, and doesn't capture the suggestion nuance well.",
          "C) said": "Too generic — loses the specific 'suggestion' function of the original.",
          "D) asked": "Would misrepresent a suggestion as a genuine question.",
        },
        grammarCategory: "REPORTED_SPEECH",
      },
      {
        order: 5,
        questionType: "MULTIPLE_CHOICE",
        prompt: "\"I did NOT take your umbrella,\" he said firmly. → He ___ taking her umbrella.",
        options: ["A) admitted", "B) denied", "C) suggested", "D) regretted"],
        correctAnswer: "B) denied",
        explanation: "'Deny doing something' reports a firm rejection of an accusation, matching 'I did NOT take...'.",
        distractorExplanations: {
          "A) admitted": "Would mean the opposite — accepting responsibility.",
          "C) suggested": "Doesn't match the meaning of a firm denial at all.",
          "D) regretted": "Would imply he did take it and feels sorry, contradicting the original statement.",
        },
        grammarCategory: "REPORTED_SPEECH",
      },
    ],
  },
  {
    slug: "grammar-relative-clauses",
    type: "GRAMMAR_DRILL",
    skill: "GRAMMAR",
    level: "B2",
    title: "Relative clauses practice",
    topic: "relative-clauses",
    instructions: "Choose the option that best completes each sentence.",
    content: {},
    questions: [
      {
        order: 1,
        questionType: "MULTIPLE_CHOICE",
        prompt: "The engineer ___ designed this bridge later won an award.",
        options: ["A) which", "B) who", "C) whom", "D) whose"],
        correctAnswer: "B) who",
        explanation: "'Who' is the subject relative pronoun for people, needed here since 'the engineer' is the subject of 'designed'.",
        distractorExplanations: {
          "A) which": "'Which' refers to things, not people.",
          "C) whom": "'Whom' is an object pronoun; here the engineer is the subject of 'designed'.",
          "D) whose": "'Whose' shows possession, which isn't the relationship here.",
        },
        grammarCategory: "RELATIVE_CLAUSES",
      },
      {
        order: 2,
        questionType: "MULTIPLE_CHOICE",
        prompt: "My sister, ___ house is just around the corner, is coming to dinner.",
        options: ["A) who", "B) which", "C) whose", "D) that"],
        correctAnswer: "C) whose",
        explanation: "'Whose' shows possession ('my sister's house'), the required relationship here.",
        distractorExplanations: {
          "A) who": "'Who' doesn't show possession on its own.",
          "B) which": "'Which' refers to things, not people, and doesn't show possession here either.",
          "D) that": "'That' cannot be used in non-defining clauses (with commas), and doesn't show possession.",
        },
        grammarCategory: "RELATIVE_CLAUSES",
      },
      {
        order: 3,
        questionType: "MULTIPLE_CHOICE",
        prompt: "The negotiations collapsed completely, ___ nobody had expected.",
        options: ["A) that", "B) what", "C) which", "D) who"],
        correctAnswer: "C) which",
        explanation: "'Which' can refer back to the whole preceding clause (the fact that negotiations collapsed), commenting on the entire situation.",
        distractorExplanations: {
          "A) that": "'That' can't be used after a comma in this non-defining, commenting structure.",
          "B) what": "'What' isn't a relative pronoun used to refer back to a previous clause like this.",
          "D) who": "'Who' refers to people, not to a whole preceding idea.",
        },
        grammarCategory: "RELATIVE_CLAUSES",
      },
      {
        order: 4,
        questionType: "MULTIPLE_CHOICE",
        prompt: "The report ___ on the table needs to be signed by Friday.",
        options: ["A) lying", "B) lies", "C) which lying", "D) lain"],
        correctAnswer: "A) lying",
        explanation: "A reduced relative clause with an -ing participle replaces 'which is lying' with active meaning.",
        distractorExplanations: {
          "B) lies": "A finite verb can't be inserted directly into the noun phrase like this without a relative pronoun.",
          "C) which lying": "Mixes a relative pronoun with a participle incorrectly — pick one structure.",
          "D) lain": "Past participle would give a passive meaning, which doesn't fit 'lying on the table'.",
        },
        grammarCategory: "RELATIVE_CLAUSES",
      },
      {
        order: 5,
        questionType: "MULTIPLE_CHOICE",
        prompt: "This is the exact spot ___ the treaty was signed.",
        options: ["A) which", "B) where", "C) that", "D) when"],
        correctAnswer: "B) where",
        explanation: "'Where' is the relative adverb used for places, referring to 'the exact spot'.",
        distractorExplanations: {
          "A) which": "Would need a preposition ('at which'); 'where' is more natural and direct here.",
          "C) that": "Would also need a preposition to express location correctly ('that...at').",
          "D) when": "'When' refers to time, not place.",
        },
        grammarCategory: "RELATIVE_CLAUSES",
      },
    ],
  },
  {
    slug: "grammar-participle-clauses",
    type: "GRAMMAR_DRILL",
    skill: "GRAMMAR",
    level: "C1",
    title: "Participle clauses practice",
    topic: "participle-clauses",
    instructions: "Choose the option that best completes each sentence.",
    content: {},
    questions: [
      {
        order: 1,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ by the noise, the dog started barking wildly.",
        options: ["A) Startling", "B) Startled", "C) To startle", "D) Having startled"],
        correctAnswer: "B) Startled",
        explanation: "Past participle expresses a passive meaning: the dog was startled by the noise.",
        distractorExplanations: {
          "A) Startling": "-ing form would give an active meaning ('the dog startling something'), which is wrong here.",
          "C) To startle": "An infinitive clause doesn't express this passive, reason-based relationship naturally.",
          "D) Having startled": "Would wrongly suggest the dog did the startling to something else beforehand.",
        },
        grammarCategory: "GERUNDS_INFINITIVES",
      },
      {
        order: 2,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ all the evidence, the jury still couldn't reach a verdict.",
        options: ["A) Considering", "B) Considered", "C) Having considered", "D) To consider"],
        correctAnswer: "C) Having considered",
        explanation: "'Having + past participle' shows the considering was completed before the main clause action (or lack of verdict).",
        distractorExplanations: {
          "A) Considering": "Simple -ing suggests simultaneous action, losing the 'already completed' nuance.",
          "B) Considered": "Passive past participle alone would suggest the jury itself was considered, not that they did the considering.",
          "D) To consider": "An infinitive doesn't fit this concessive, completed-action meaning.",
        },
        grammarCategory: "GERUNDS_INFINITIVES",
      },
      {
        order: 3,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ in a remote village, she had never used the internet until she was eighteen.",
        options: ["A) Raising", "B) Raised", "C) To raise", "D) Having raised"],
        correctAnswer: "B) Raised",
        explanation: "Past participle gives a passive meaning: she was raised in a remote village.",
        distractorExplanations: {
          "A) Raising": "-ing would give an active meaning, implying she raised something/someone else.",
          "C) To raise": "An infinitive doesn't fit this background/reason structure.",
          "D) Having raised": "Would wrongly imply she actively raised someone else before the main clause.",
        },
        grammarCategory: "GERUNDS_INFINITIVES",
      },
      {
        order: 4,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ that the flight was delayed, we decided to get some dinner.",
        options: ["A) Realize", "B) Realizing", "C) Realized", "D) To realize"],
        correctAnswer: "B) Realizing",
        explanation: "-ing participle clause gives an active meaning: we realised, then decided.",
        distractorExplanations: {
          "A) Realize": "Base form can't start a participle clause like this.",
          "C) Realized": "Past participle would give a passive meaning ('we were realized'), which makes no sense.",
          "D) To realize": "Infinitive would express purpose, not the reason/cause relationship intended here.",
        },
        grammarCategory: "GERUNDS_INFINITIVES",
      },
      {
        order: 5,
        questionType: "MULTIPLE_CHOICE",
        prompt: "The proposal, ___ by three separate departments, was finally approved.",
        options: ["A) reviewing", "B) reviewed", "C) review", "D) to review"],
        correctAnswer: "B) reviewed",
        explanation: "A reduced non-defining relative clause with passive meaning: the proposal was reviewed.",
        distractorExplanations: {
          "A) reviewing": "-ing would give an active meaning, implying the proposal reviewed something.",
          "C) review": "Base form can't be inserted directly like this.",
          "D) to review": "Infinitive doesn't fit this descriptive, passive relative-clause meaning.",
        },
        grammarCategory: "PASSIVE_VOICE",
      },
    ],
  },
  {
    slug: "grammar-gerunds-infinitives",
    type: "GRAMMAR_DRILL",
    skill: "GRAMMAR",
    level: "B2",
    title: "Gerunds and infinitives practice",
    topic: "gerunds-infinitives",
    instructions: "Choose the option that best completes each sentence.",
    content: {},
    questions: [
      {
        order: 1,
        questionType: "MULTIPLE_CHOICE",
        prompt: "Don't forget ___ the lights before you leave.",
        options: ["A) turning off", "B) to turn off", "C) turn off", "D) having turned off"],
        correctAnswer: "B) to turn off",
        explanation: "'Forget to do' refers to a future obligation not yet completed — a reminder.",
        distractorExplanations: {
          "A) turning off": "'Forget doing' refers to forgetting a past action, not a future reminder.",
          "C) turn off": "Not a valid pattern after 'forget' without 'to'.",
          "D) having turned off": "Wrongly implies the action is already completed.",
        },
        grammarCategory: "GERUNDS_INFINITIVES",
      },
      {
        order: 2,
        questionType: "MULTIPLE_CHOICE",
        prompt: "I'll never forget ___ the northern lights for the first time.",
        options: ["A) to see", "B) seeing", "C) see", "D) having see"],
        correctAnswer: "B) seeing",
        explanation: "'Forget doing' refers to a memory of a past action/experience.",
        distractorExplanations: {
          "A) to see": "'Forget to do' refers to a future obligation, not a past memory.",
          "C) see": "Not a valid pattern after 'forget'.",
          "D) having see": "Incorrect form — should be 'having seen', and still less natural than the simple gerund here.",
        },
        grammarCategory: "GERUNDS_INFINITIVES",
      },
      {
        order: 3,
        questionType: "MULTIPLE_CHOICE",
        prompt: "We stopped ___ coffee on the way to the meeting.",
        options: ["A) buying", "B) to buy", "C) buy", "D) bought"],
        correctAnswer: "B) to buy",
        explanation: "'Stop to do' means pausing one activity in order to do another (buying coffee was the purpose of stopping).",
        distractorExplanations: {
          "A) buying": "'Stop doing' would mean ceasing the activity of buying coffee, which doesn't fit the context.",
          "C) buy": "Not a valid pattern after 'stopped' without 'to'.",
          "D) bought": "Past tense doesn't fit this infinitive-of-purpose structure.",
        },
        grammarCategory: "GERUNDS_INFINITIVES",
      },
      {
        order: 4,
        questionType: "MULTIPLE_CHOICE",
        prompt: "She regrets ___ so harshly to her colleague last week.",
        options: ["A) to speak", "B) speaking", "C) speak", "D) having speak"],
        correctAnswer: "B) speaking",
        explanation: "'Regret doing' refers to feeling sorry about a past action, matching 'last week'.",
        distractorExplanations: {
          "A) to speak": "'Regret to say/inform' is a fixed formal pattern for bad news being delivered now, not for past regret.",
          "C) speak": "Not a valid pattern after 'regrets'.",
          "D) having speak": "Incorrect form; even 'having spoken' would be unnecessarily complex next to the natural gerund.",
        },
        grammarCategory: "GERUNDS_INFINITIVES",
      },
      {
        order: 5,
        questionType: "MULTIPLE_CHOICE",
        prompt: "I regret ___ you that your application has been unsuccessful.",
        options: ["A) informing", "B) to inform", "C) inform", "D) informed"],
        correctAnswer: "B) to inform",
        explanation: "'Regret to inform/say' is the fixed formal pattern for announcing unwelcome news at the moment of speaking.",
        distractorExplanations: {
          "A) informing": "'Regret doing' would refer to a past action, not this formal announcement pattern.",
          "C) inform": "Not a valid pattern after 'regret' without 'to'.",
          "D) informed": "Past form doesn't fit the infinitive structure required here.",
        },
        grammarCategory: "GERUNDS_INFINITIVES",
      },
    ],
  },
  {
    slug: "grammar-inversion",
    type: "GRAMMAR_DRILL",
    skill: "GRAMMAR",
    level: "C1",
    title: "Inversion practice",
    topic: "inversion",
    instructions: "Choose the option that best completes each sentence.",
    content: {},
    questions: [
      {
        order: 1,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ such a compelling argument before.",
        options: ["A) Never I have heard", "B) Never have I heard", "C) I have never heard", "D) Never did I heard"],
        correctAnswer: "B) Never have I heard",
        explanation: "Fronting 'Never' triggers auxiliary-subject inversion: Never have I heard.",
        distractorExplanations: {
          "A) Never I have heard": "Wrong word order — the auxiliary must come before the subject.",
          "C) I have never heard": "Correct grammatically, but doesn't use inversion, which this exercise targets.",
          "D) Never did I heard": "'Did' requires the base form 'hear', not 'heard'.",
        },
        grammarCategory: "INVERSION",
      },
      {
        order: 2,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ had she started the presentation than the projector broke.",
        options: ["A) No sooner", "B) Hardly", "C) Barely", "D) Scarcely"],
        correctAnswer: "A) No sooner",
        explanation: "'No sooner...than' is the fixed pattern for two events in quick succession (the others pair with 'when', not 'than').",
        distractorExplanations: {
          "B) Hardly": "'Hardly' pairs with 'when', not 'than'.",
          "C) Barely": "'Barely' pairs with 'when', not 'than'.",
          "D) Scarcely": "'Scarcely' pairs with 'when', not 'than'.",
        },
        grammarCategory: "INVERSION",
      },
      {
        order: 3,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ should this door be left unlocked overnight.",
        options: ["A) Under no circumstances", "B) In no circumstances", "C) With no circumstances", "D) At no circumstances"],
        correctAnswer: "A) Under no circumstances",
        explanation: "'Under no circumstances' is the fixed negative adverbial phrase that triggers inversion.",
        distractorExplanations: {
          "B) In no circumstances": "Not the standard preposition used in this fixed phrase.",
          "C) With no circumstances": "Not a standard English collocation.",
          "D) At no circumstances": "Not the standard preposition used in this fixed phrase.",
        },
        grammarCategory: "INVERSION",
      },
      {
        order: 4,
        questionType: "MULTIPLE_CHOICE",
        prompt: "Rarely ___ such dedication from a new employee.",
        options: ["A) we see", "B) do we see", "C) we do see", "D) see we"],
        correctAnswer: "B) do we see",
        explanation: "Fronting 'Rarely' triggers inversion with the auxiliary 'do': Rarely do we see.",
        distractorExplanations: {
          "A) we see": "No inversion — incorrect after a fronted negative adverbial.",
          "C) we do see": "Wrong word order — the auxiliary must come before the subject.",
          "D) see we": "Missing the required auxiliary 'do' before the subject.",
        },
        grammarCategory: "INVERSION",
      },
      {
        order: 5,
        questionType: "MULTIPLE_CHOICE",
        prompt: "Not only ___ late, but he also forgot the documents.",
        options: ["A) he was", "B) was he", "C) he did", "D) did he was"],
        correctAnswer: "B) was he",
        explanation: "Fronting 'Not only' triggers inversion: Not only was he late.",
        distractorExplanations: {
          "A) he was": "No inversion — incorrect after fronted 'Not only'.",
          "C) he did": "Wrong auxiliary — 'was' is needed to invert with 'late' (an adjective), not 'did'.",
          "D) did he was": "Mixes two auxiliaries incorrectly.",
        },
        grammarCategory: "INVERSION",
      },
    ],
  },
  {
    slug: "grammar-cleft-sentences",
    type: "GRAMMAR_DRILL",
    skill: "GRAMMAR",
    level: "C1",
    title: "Cleft sentences practice",
    topic: "cleft-sentences",
    instructions: "Choose the option that best completes each sentence.",
    content: {},
    questions: [
      {
        order: 1,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ the manager who approved the budget, not the finance team.",
        options: ["A) It was", "B) It is", "C) There was", "D) That was"],
        correctAnswer: "A) It was",
        explanation: "'It was...who' is the cleft structure emphasising 'the manager' as the one who approved it (past event).",
        distractorExplanations: {
          "B) It is": "Present tense doesn't fit a completed past action ('approved').",
          "C) There was": "'There was' introduces existence, not emphasis on a specific agent.",
          "D) That was": "'That' doesn't combine with 'who' in this standard cleft pattern.",
        },
        grammarCategory: "OTHER",
      },
      {
        order: 2,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ surprised me most was how calmly she handled the crisis.",
        options: ["A) It", "B) That", "C) What", "D) Which"],
        correctAnswer: "C) What",
        explanation: "'What + clause + is/was...' is the standard cleft pattern emphasising the whole idea that follows.",
        distractorExplanations: {
          "A) It": "'It' clefts use 'It is/was + X + that', not this structure with a verb directly after.",
          "B) That": "'That' doesn't start this kind of cleft sentence.",
          "D) Which": "'Which' isn't used to begin a cleft sentence like this.",
        },
        grammarCategory: "OTHER",
      },
      {
        order: 3,
        questionType: "MULTIPLE_CHOICE",
        prompt: "It is the lack of investment ___ is holding the project back.",
        options: ["A) who", "B) that", "C) what", "D) whom"],
        correctAnswer: "B) that",
        explanation: "'It is X that...' uses 'that' for things (lack of investment), not 'who/whom' which refer to people.",
        distractorExplanations: {
          "A) who": "'Who' refers to people, not 'the lack of investment'.",
          "C) what": "'What' isn't used in this position within an 'It is...that' cleft.",
          "D) whom": "'Whom' refers to people, not things.",
        },
        grammarCategory: "OTHER",
      },
      {
        order: 4,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ we need right now is a clear, realistic plan.",
        options: ["A) What", "B) It", "C) That", "D) There"],
        correctAnswer: "A) What",
        explanation: "'What + subject + verb + is...' is the cleft pattern emphasising the thing that is needed.",
        distractorExplanations: {
          "B) It": "'It' clefts have a different structure ('It is X that we need'), not this one.",
          "C) That": "'That' doesn't begin this kind of cleft sentence.",
          "D) There": "'There' introduces existence, not emphasis on a specific need.",
        },
        grammarCategory: "OTHER",
      },
      {
        order: 5,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ was in 2019 that the company first became profitable.",
        options: ["A) It", "B) This", "C) That", "D) There"],
        correctAnswer: "A) It",
        explanation: "'It was in [time] that...' is the standard cleft pattern emphasising a specific time.",
        distractorExplanations: {
          "B) This": "'This' isn't used to introduce this type of cleft sentence.",
          "C) That": "'That' doesn't start the sentence in this pattern; it appears later, after the emphasised element.",
          "D) There": "'There' introduces existence, not emphasis on a time.",
        },
        grammarCategory: "OTHER",
      },
    ],
  },
  {
    slug: "grammar-determiners-articles",
    type: "GRAMMAR_DRILL",
    skill: "GRAMMAR",
    level: "B2",
    title: "Determiners and articles practice",
    topic: "determiners-articles",
    instructions: "Choose the option that best completes each sentence.",
    content: {},
    questions: [
      {
        order: 1,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ education is the key to reducing poverty worldwide.",
        options: ["A) The", "B) An", "C) — (no article)", "D) A"],
        correctAnswer: "C) — (no article)",
        explanation: "General, uncountable statement about education as a concept requires no article.",
        distractorExplanations: {
          "A) The": "'The' would specify a particular, known instance of education, not the general concept.",
          "B) An": "'Education' is uncountable and doesn't take 'an'.",
          "D) A": "'Education' is uncountable and doesn't take 'a'.",
        },
        grammarCategory: "ARTICLES",
      },
      {
        order: 2,
        questionType: "MULTIPLE_CHOICE",
        prompt: "I have never seen ___ such beautiful sunset.",
        options: ["A) such", "B) such a", "C) so", "D) so a"],
        correctAnswer: "B) such a",
        explanation: "'Such a/an + adjective + singular countable noun' requires the indefinite article.",
        distractorExplanations: {
          "A) such": "'Such' alone before a singular countable noun needs 'a/an' as well.",
          "C) so": "'So' would need a different structure ('so beautiful a sunset'), not this word order.",
          "D) so a": "Not a standard English structure.",
        },
        grammarCategory: "ARTICLES",
      },
      {
        order: 3,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ education she received abroad shaped her entire career.",
        options: ["A) —", "B) An", "C) The", "D) A"],
        correctAnswer: "C) The",
        explanation: "'The' is needed because 'education' is now specified by 'she received abroad' — a known, particular instance.",
        distractorExplanations: {
          "A) —": "No article would lose the specific reference created by 'she received abroad'.",
          "B) An": "'Education' is uncountable and doesn't take 'an'.",
          "D) A": "'Education' is uncountable and doesn't take 'a'.",
        },
        grammarCategory: "ARTICLES",
      },
      {
        order: 4,
        questionType: "MULTIPLE_CHOICE",
        prompt: "We travelled ___ night to avoid the traffic.",
        options: ["A) by the", "B) at the", "C) by", "D) at"],
        correctAnswer: "D) at",
        explanation: "'At night' is a fixed time expression with no article.",
        distractorExplanations: {
          "A) by the": "'By the night' is not a standard fixed expression here.",
          "B) at the": "'At night' as a general time expression doesn't take 'the'.",
          "C) by": "'By night' exists but is more literary/less common than the standard 'at night'; the exercise targets the more common form.",
        },
        grammarCategory: "ARTICLES",
      },
      {
        order: 5,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ whole, the conference was a success, despite a few technical problems.",
        options: ["A) At the", "B) On the", "C) In the", "D) By the"],
        correctAnswer: "B) On the",
        explanation: "'On the whole' is a fixed expression meaning 'generally speaking'.",
        distractorExplanations: {
          "A) At the": "Not the correct preposition in this fixed expression.",
          "C) In the": "Not the correct preposition in this fixed expression.",
          "D) By the": "Not the correct preposition in this fixed expression.",
        },
        grammarCategory: "ARTICLES",
      },
    ],
  },
  {
    slug: "grammar-prepositions",
    type: "GRAMMAR_DRILL",
    skill: "GRAMMAR",
    level: "B2",
    title: "Prepositions practice",
    topic: "prepositions",
    instructions: "Choose the option that best completes each sentence.",
    content: {},
    questions: [
      {
        order: 1,
        questionType: "MULTIPLE_CHOICE",
        prompt: "She is responsible ___ the entire marketing budget.",
        options: ["A) of", "B) for", "C) with", "D) to"],
        correctAnswer: "B) for",
        explanation: "'Responsible for' is the correct fixed dependent preposition.",
        distractorExplanations: {
          "A) of": "Common error, often from direct translation, but not correct in English.",
          "C) with": "Not the correct dependent preposition for 'responsible'.",
          "D) to": "'Responsible to someone' exists (reporting relationship) but not for a budget/task like this.",
        },
        grammarCategory: "PREPOSITIONS",
      },
      {
        order: 2,
        questionType: "MULTIPLE_CHOICE",
        prompt: "He insisted ___ paying for everyone's dinner.",
        options: ["A) in", "B) at", "C) on", "D) for"],
        correctAnswer: "C) on",
        explanation: "'Insist on doing something' is the fixed dependent preposition.",
        distractorExplanations: {
          "A) in": "Not the correct dependent preposition for 'insist'.",
          "B) at": "Not the correct dependent preposition for 'insist'.",
          "D) for": "Not the correct dependent preposition for 'insist'.",
        },
        grammarCategory: "PREPOSITIONS",
      },
      {
        order: 3,
        questionType: "MULTIPLE_CHOICE",
        prompt: "The success of the project depends heavily ___ careful planning.",
        options: ["A) of", "B) on", "C) from", "D) with"],
        correctAnswer: "B) on",
        explanation: "'Depend on' is the fixed dependent preposition.",
        distractorExplanations: {
          "A) of": "Not the correct dependent preposition for 'depend'.",
          "C) from": "Not the correct dependent preposition for 'depend'.",
          "D) with": "Not the correct dependent preposition for 'depend'.",
        },
        grammarCategory: "PREPOSITIONS",
      },
      {
        order: 4,
        questionType: "MULTIPLE_CHOICE",
        prompt: "The committee is made up ___ representatives from every department.",
        options: ["A) of", "B) from", "C) with", "D) by"],
        correctAnswer: "A) of",
        explanation: "'Made up of' is the fixed phrase meaning 'consists of/composed of'.",
        distractorExplanations: {
          "B) from": "Not the correct preposition in this fixed phrase.",
          "C) with": "Not the correct preposition in this fixed phrase.",
          "D) by": "Not the correct preposition in this fixed phrase.",
        },
        grammarCategory: "PREPOSITIONS",
      },
      {
        order: 5,
        questionType: "MULTIPLE_CHOICE",
        prompt: "She's been married ___ him for almost twenty years.",
        options: ["A) with", "B) to", "C) for", "D) at"],
        correctAnswer: "B) to",
        explanation: "'Married to someone' is the fixed dependent preposition.",
        distractorExplanations: {
          "A) with": "Common error from other languages, but not correct in English.",
          "C) for": "Not the correct dependent preposition for 'married'.",
          "D) at": "Not the correct dependent preposition for 'married'.",
        },
        grammarCategory: "PREPOSITIONS",
      },
    ],
  },
  {
    slug: "grammar-linking-devices",
    type: "GRAMMAR_DRILL",
    skill: "GRAMMAR",
    level: "C1",
    title: "Linking devices and cohesion practice",
    topic: "linking-devices",
    instructions: "Choose the option that best completes each sentence.",
    content: {},
    questions: [
      {
        order: 1,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ the budget was extremely limited, the team delivered an excellent campaign.",
        options: ["A) Despite", "B) Although", "C) In spite of", "D) Because of"],
        correctAnswer: "B) Although",
        explanation: "'Although' is followed by a full clause (subject + verb); 'Despite/In spite of' need a noun phrase instead.",
        distractorExplanations: {
          "A) Despite": "Despite is followed by a noun phrase, not a full clause like 'the budget was...'.",
          "C) In spite of": "Same issue as 'Despite' — needs a noun phrase, not a clause.",
          "D) Because of": "Wrong logical relationship — this needs a contrast, not a cause.",
        },
        grammarCategory: "OTHER",
      },
      {
        order: 2,
        questionType: "MULTIPLE_CHOICE",
        prompt: "___ the limited budget, the team delivered an excellent campaign.",
        options: ["A) Although", "B) Despite", "C) Even though", "D) While"],
        correctAnswer: "B) Despite",
        explanation: "'Despite' is followed by a noun phrase ('the limited budget'), not a full clause.",
        distractorExplanations: {
          "A) Although": "'Although' needs a full clause with a verb, not just a noun phrase.",
          "C) Even though": "Also needs a full clause, not a noun phrase.",
          "D) While": "Also needs a full clause, not a noun phrase, in this contrastive sense.",
        },
        grammarCategory: "OTHER",
      },
      {
        order: 3,
        questionType: "MULTIPLE_CHOICE",
        prompt: "You may attend the event, ___ you register in advance.",
        options: ["A) unless", "B) provided that", "C) despite", "D) whereas"],
        correctAnswer: "B) provided that",
        explanation: "'Provided that' introduces a necessary condition, matching 'you may attend...if this condition is met'.",
        distractorExplanations: {
          "A) unless": "'Unless' means 'except if', which reverses the intended condition.",
          "C) despite": "'Despite' introduces contrast, not a condition, and needs a noun phrase.",
          "D) whereas": "'Whereas' introduces contrast between two facts, not a condition.",
        },
        grammarCategory: "OTHER",
      },
      {
        order: 4,
        questionType: "MULTIPLE_CHOICE",
        prompt: "Sales fell in the first quarter; ___, profits actually increased due to lower costs.",
        options: ["A) moreover", "B) nonetheless", "C) furthermore", "D) similarly"],
        correctAnswer: "B) nonetheless",
        explanation: "'Nonetheless' signals contrast (an unexpected result despite falling sales), matching 'profits actually increased'.",
        distractorExplanations: {
          "A) moreover": "'Moreover' adds a similar point, but this sentence needs a contrast, not an addition.",
          "C) furthermore": "Same problem — adds information rather than contrasting it.",
          "D) similarly": "Would incorrectly signal the two facts are alike, when they actually contrast.",
        },
        grammarCategory: "OTHER",
      },
      {
        order: 5,
        questionType: "MULTIPLE_CHOICE",
        prompt: "The proposal was rejected ___ its high cost was never fully justified.",
        options: ["A) on the grounds that", "B) provided that", "C) as opposed to", "D) in addition to"],
        correctAnswer: "A) on the grounds that",
        explanation: "'On the grounds that' introduces the reason for a decision (why it was rejected).",
        distractorExplanations: {
          "B) provided that": "Introduces a condition, not a reason for a past decision.",
          "C) as opposed to": "Introduces a contrast between two options, not a reason.",
          "D) in addition to": "Introduces an addition, not a reason, and needs a noun phrase.",
        },
        grammarCategory: "OTHER",
      },
    ],
  },
];
