export type VocabWordSeed = {
  word: string;
  definition: string;
  translation?: string;
  exampleSentence: string;
  synonyms?: string[];
  antonyms?: string[];
  collocations?: string[];
  phrasalVerbs?: string[];
  pronunciationIPA?: string;
  category?: string;
  cefrLevel: "B1" | "B2" | "C1" | "C2";
};

export const vocabularyWords: VocabWordSeed[] = [
  // --- academic / general C1 ---
  {
    word: "substantial",
    definition: "Large in amount, size or importance.",
    translation: "sustancial / considerable",
    exampleSentence: "There has been a substantial increase in remote job applications.",
    synonyms: ["considerable", "significant", "sizeable"],
    antonyms: ["negligible", "insignificant"],
    collocations: ["substantial increase", "substantial evidence", "substantial amount"],
    pronunciationIPA: "/səbˈstæn.ʃəl/",
    category: "academic",
    cefrLevel: "C1",
  },
  {
    word: "unprecedented",
    definition: "Never having happened or existed before.",
    translation: "sin precedentes",
    exampleSentence: "The company faced unprecedented demand during the holiday season.",
    synonyms: ["unparalleled", "unheard of"],
    antonyms: ["common", "typical"],
    collocations: ["unprecedented levels", "unprecedented growth"],
    pronunciationIPA: "/ʌnˈpres.ɪ.den.tɪd/",
    category: "academic",
    cefrLevel: "C1",
  },
  {
    word: "meticulous",
    definition: "Showing great attention to detail; very careful and precise.",
    translation: "meticuloso",
    exampleSentence: "She is meticulous about checking every figure in the report.",
    synonyms: ["thorough", "painstaking", "scrupulous"],
    antonyms: ["careless", "sloppy"],
    collocations: ["meticulous attention to detail", "meticulous planning"],
    pronunciationIPA: "/məˈtɪk.jə.ləs/",
    category: "personality",
    cefrLevel: "C1",
  },
  {
    word: "ubiquitous",
    definition: "Present, appearing, or found everywhere.",
    translation: "ubicuo / omnipresente",
    exampleSentence: "Smartphones have become ubiquitous in modern society.",
    synonyms: ["omnipresent", "pervasive"],
    antonyms: ["rare", "scarce"],
    collocations: ["ubiquitous presence", "increasingly ubiquitous"],
    pronunciationIPA: "/juːˈbɪk.wɪ.təs/",
    category: "academic",
    cefrLevel: "C1",
  },
  {
    word: "ambiguous",
    definition: "Open to more than one interpretation; not clear or decided.",
    translation: "ambiguo",
    exampleSentence: "The contract's wording on overtime pay was deliberately ambiguous.",
    synonyms: ["vague", "equivocal"],
    antonyms: ["clear", "unambiguous"],
    collocations: ["ambiguous statement", "morally ambiguous"],
    pronunciationIPA: "/æmˈbɪɡ.ju.əs/",
    category: "academic",
    cefrLevel: "C1",
  },
  {
    word: "plausible",
    definition: "Seeming reasonable or probable.",
    translation: "plausible / verosímil",
    exampleSentence: "The detective offered a plausible explanation for the missing evidence.",
    synonyms: ["credible", "believable"],
    antonyms: ["implausible", "far-fetched"],
    collocations: ["plausible explanation", "highly plausible"],
    pronunciationIPA: "/ˈplɔː.zə.bəl/",
    category: "academic",
    cefrLevel: "C1",
  },
  {
    word: "resilient",
    definition: "Able to recover quickly from difficulties; tough.",
    translation: "resiliente",
    exampleSentence: "The local economy proved remarkably resilient after the factory closures.",
    synonyms: ["tough", "hardy", "adaptable"],
    antonyms: ["fragile", "vulnerable"],
    collocations: ["remarkably resilient", "resilient economy"],
    pronunciationIPA: "/rɪˈzɪl.i.ənt/",
    category: "personality",
    cefrLevel: "C1",
  },
  {
    word: "detrimental",
    definition: "Tending to cause harm.",
    translation: "perjudicial",
    exampleSentence: "Long working hours can be detrimental to employees' mental health.",
    synonyms: ["harmful", "damaging"],
    antonyms: ["beneficial", "advantageous"],
    collocations: ["detrimental effect", "detrimental to health"],
    pronunciationIPA: "/ˌdet.rɪˈmen.təl/",
    category: "academic",
    cefrLevel: "C1",
  },

  // --- work / business ---
  {
    word: "to bring about",
    definition: "To cause something to happen.",
    translation: "provocar / dar lugar a",
    exampleSentence: "The new law brought about significant changes in the industry.",
    synonyms: ["cause", "trigger", "generate"],
    antonyms: ["prevent"],
    collocations: ["bring about change", "bring about a crisis"],
    phrasalVerbs: ["bring about"],
    pronunciationIPA: "/brɪŋ əˈbaʊt/",
    category: "work",
    cefrLevel: "C1",
  },
  {
    word: "to fall through",
    definition: "(of a plan) to fail to happen.",
    translation: "fracasar / no llevarse a cabo",
    exampleSentence: "Our merger talks fell through at the last minute.",
    synonyms: ["fail", "collapse"],
    antonyms: ["succeed", "go ahead"],
    collocations: ["the deal fell through", "plans fell through"],
    phrasalVerbs: ["fall through"],
    pronunciationIPA: "/fɔːl θruː/",
    category: "work",
    cefrLevel: "B2",
  },
  {
    word: "to weigh up",
    definition: "To consider something carefully before making a decision.",
    translation: "sopesar",
    exampleSentence: "We need to weigh up the pros and cons before signing the contract.",
    synonyms: ["consider", "evaluate"],
    collocations: ["weigh up the options", "weigh up the risks"],
    phrasalVerbs: ["weigh up"],
    pronunciationIPA: "/weɪ ʌp/",
    category: "work",
    cefrLevel: "B2",
  },
  {
    word: "to spearhead",
    definition: "To lead an initiative or campaign.",
    translation: "encabezar / liderar",
    exampleSentence: "She was asked to spearhead the company's expansion into Asia.",
    synonyms: ["lead", "head up"],
    collocations: ["spearhead a campaign", "spearhead an initiative"],
    pronunciationIPA: "/ˈspɪər.hed/",
    category: "work",
    cefrLevel: "C1",
  },
  {
    word: "streamline",
    definition: "To make a process more efficient by removing unnecessary steps.",
    translation: "optimizar / agilizar",
    exampleSentence: "The new software streamlines the entire invoicing process.",
    synonyms: ["simplify", "optimise"],
    antonyms: ["complicate"],
    collocations: ["streamline a process", "streamline operations"],
    pronunciationIPA: "/ˈstriːm.laɪn/",
    category: "work",
    cefrLevel: "C1",
  },
  {
    word: "to touch base",
    definition: "To make brief contact with someone, often to check on progress.",
    translation: "ponerse en contacto brevemente",
    exampleSentence: "Let's touch base next week once you've reviewed the proposal.",
    synonyms: ["check in", "get in touch"],
    collocations: ["touch base with someone"],
    pronunciationIPA: "/tʌtʃ beɪs/",
    category: "work",
    cefrLevel: "B2",
  },
  {
    word: "leverage",
    definition: "To use something to maximum advantage.",
    translation: "aprovechar / sacar partido de",
    exampleSentence: "The startup leveraged its founder's reputation to attract early investors.",
    synonyms: ["exploit", "capitalise on"],
    collocations: ["leverage experience", "leverage technology"],
    pronunciationIPA: "/ˈliː.vər.ɪdʒ/",
    category: "work",
    cefrLevel: "C1",
  },

  // --- environment ---
  {
    word: "to phase out",
    definition: "To gradually stop using or producing something.",
    translation: "eliminar gradualmente",
    exampleSentence: "The government plans to phase out petrol cars by 2035.",
    synonyms: ["discontinue gradually"],
    antonyms: ["introduce", "phase in"],
    collocations: ["phase out a product", "phase out subsidies"],
    phrasalVerbs: ["phase out"],
    pronunciationIPA: "/feɪz aʊt/",
    category: "environment",
    cefrLevel: "C1",
  },
  {
    word: "sustainable",
    definition: "Able to continue over time without depleting resources.",
    translation: "sostenible",
    exampleSentence: "The company switched to sustainable packaging last year.",
    synonyms: ["renewable", "eco-friendly"],
    antonyms: ["unsustainable"],
    collocations: ["sustainable development", "sustainable practices"],
    pronunciationIPA: "/səˈsteɪ.nə.bəl/",
    category: "environment",
    cefrLevel: "B2",
  },
  {
    word: "depletion",
    definition: "The reduction of resources by using them up.",
    translation: "agotamiento",
    exampleSentence: "Overfishing has led to the depletion of local fish stocks.",
    synonyms: ["exhaustion", "reduction"],
    antonyms: ["replenishment"],
    collocations: ["resource depletion", "ozone depletion"],
    pronunciationIPA: "/dɪˈpliː.ʃən/",
    category: "environment",
    cefrLevel: "C1",
  },
  {
    word: "to offset",
    definition: "To counteract something by having an equal and opposite effect.",
    translation: "compensar",
    exampleSentence: "The airline offers to offset your flight's carbon emissions.",
    synonyms: ["counterbalance", "compensate for"],
    collocations: ["offset emissions", "offset the cost"],
    pronunciationIPA: "/ˈɒf.set/",
    category: "environment",
    cefrLevel: "C1",
  },
  {
    word: "renewable",
    definition: "(of energy) able to be replenished naturally.",
    translation: "renovable",
    exampleSentence: "The country now generates most of its electricity from renewable sources.",
    synonyms: ["sustainable"],
    antonyms: ["non-renewable"],
    collocations: ["renewable energy", "renewable resources"],
    pronunciationIPA: "/rɪˈnjuː.ə.bəl/",
    category: "environment",
    cefrLevel: "B2",
  },

  // --- technology ---
  {
    word: "glitch",
    definition: "A minor malfunction or problem, especially in a machine or system.",
    translation: "fallo técnico",
    exampleSentence: "A glitch in the payment system meant some customers were charged twice.",
    synonyms: ["bug", "malfunction"],
    collocations: ["technical glitch", "software glitch"],
    pronunciationIPA: "/ɡlɪtʃ/",
    category: "technology",
    cefrLevel: "B2",
  },
  {
    word: "to roll out",
    definition: "To make a new product or service available for the first time.",
    translation: "lanzar / implementar",
    exampleSentence: "The company plans to roll out the update to all users next week.",
    synonyms: ["launch", "release"],
    phrasalVerbs: ["roll out"],
    collocations: ["roll out a feature", "roll out an update"],
    pronunciationIPA: "/rəʊl aʊt/",
    category: "technology",
    cefrLevel: "B2",
  },
  {
    word: "cutting-edge",
    definition: "Extremely modern and advanced.",
    translation: "puntero / de vanguardia",
    exampleSentence: "The hospital invested in cutting-edge diagnostic equipment.",
    synonyms: ["state-of-the-art", "innovative"],
    antonyms: ["outdated", "obsolete"],
    collocations: ["cutting-edge technology", "cutting-edge research"],
    pronunciationIPA: "/ˌkʌt.ɪŋ ˈedʒ/",
    category: "technology",
    cefrLevel: "C1",
  },
  {
    word: "obsolete",
    definition: "No longer produced or used; out of date.",
    translation: "obsoleto",
    exampleSentence: "That model of printer became obsolete within a couple of years.",
    synonyms: ["outdated", "antiquated"],
    antonyms: ["cutting-edge", "current"],
    collocations: ["rapidly obsolete", "rendered obsolete"],
    pronunciationIPA: "/ˈɒb.sə.liːt/",
    category: "technology",
    cefrLevel: "C1",
  },
  {
    word: "to tamper with",
    definition: "To interfere with something in order to change it, often illegally.",
    translation: "manipular / alterar",
    exampleSentence: "Someone had tampered with the security camera footage.",
    synonyms: ["meddle with", "interfere with"],
    phrasalVerbs: ["tamper with"],
    collocations: ["tamper with evidence", "tamper with a device"],
    pronunciationIPA: "/ˈtæm.pər wɪð/",
    category: "technology",
    cefrLevel: "C1",
  },

  // --- relationships / personality ---
  {
    word: "to come across as",
    definition: "To give a particular impression.",
    translation: "dar la impresión de",
    exampleSentence: "He came across as very confident during the interview.",
    synonyms: ["appear", "seem"],
    phrasalVerbs: ["come across as"],
    collocations: ["come across as arrogant", "come across as genuine"],
    pronunciationIPA: "/kʌm əˈkrɒs æz/",
    category: "personality",
    cefrLevel: "C1",
  },
  {
    word: "to fall out",
    definition: "To have an argument and stop being friendly with someone.",
    translation: "pelearse / enemistarse",
    exampleSentence: "The two business partners fell out over money.",
    synonyms: ["have a falling-out", "quarrel"],
    antonyms: ["make up"],
    phrasalVerbs: ["fall out"],
    collocations: ["fall out with someone"],
    pronunciationIPA: "/fɔːl aʊt/",
    category: "relationships",
    cefrLevel: "B2",
  },
  {
    word: "candid",
    definition: "Truthful and straightforward; frank.",
    translation: "franco / sincero",
    exampleSentence: "She gave a candid account of the challenges she'd faced.",
    synonyms: ["frank", "honest"],
    antonyms: ["evasive", "guarded"],
    collocations: ["candid answer", "remarkably candid"],
    pronunciationIPA: "/ˈkæn.dɪd/",
    category: "personality",
    cefrLevel: "C1",
  },
  {
    word: "to make amends",
    definition: "To do something to correct a past wrong.",
    translation: "enmendar / reparar el daño",
    exampleSentence: "He tried to make amends by apologising publicly.",
    synonyms: ["compensate", "make up for"],
    collocations: ["make amends for", "try to make amends"],
    pronunciationIPA: "/meɪk əˈmendz/",
    category: "relationships",
    cefrLevel: "C1",
  },
  {
    word: "assertive",
    definition: "Confident and direct in expressing opinions without being aggressive.",
    translation: "asertivo",
    exampleSentence: "She's learned to be more assertive when negotiating her salary.",
    synonyms: ["confident", "self-assured"],
    antonyms: ["timid", "passive"],
    collocations: ["assertive communication", "increasingly assertive"],
    pronunciationIPA: "/əˈsɜː.tɪv/",
    category: "personality",
    cefrLevel: "C1",
  },

  // --- media / communication ---
  {
    word: "to blow out of proportion",
    definition: "To make something seem more important or serious than it really is.",
    translation: "exagerar / sacar de contexto",
    exampleSentence: "The media blew the incident out of proportion.",
    synonyms: ["exaggerate", "overstate"],
    collocations: ["blown out of all proportion"],
    pronunciationIPA: "/bləʊ aʊt əv prəˈpɔːʃ.ən/",
    category: "media",
    cefrLevel: "C1",
  },
  {
    word: "misleading",
    definition: "Giving a wrong idea or impression.",
    translation: "engañoso",
    exampleSentence: "The advert's claims were found to be misleading.",
    synonyms: ["deceptive", "confusing"],
    antonyms: ["accurate", "clear"],
    collocations: ["deliberately misleading", "misleading headline"],
    pronunciationIPA: "/ˌmɪsˈliː.dɪŋ/",
    category: "media",
    cefrLevel: "B2",
  },
  {
    word: "credible",
    definition: "Able to be believed; convincing.",
    translation: "creíble",
    exampleSentence: "The journalist relied on several credible sources.",
    synonyms: ["believable", "plausible"],
    antonyms: ["dubious", "implausible"],
    collocations: ["credible source", "credible evidence"],
    pronunciationIPA: "/ˈkred.ə.bəl/",
    category: "media",
    cefrLevel: "B2",
  },
  {
    word: "to spark",
    definition: "To cause something (like a debate or reaction) to start suddenly.",
    translation: "desatar / provocar",
    exampleSentence: "The announcement sparked a heated debate online.",
    synonyms: ["trigger", "ignite"],
    collocations: ["spark controversy", "spark a debate"],
    pronunciationIPA: "/spɑːk/",
    category: "media",
    cefrLevel: "C1",
  },

  // --- health / education ---
  {
    word: "to burn out",
    definition: "To become exhausted from overwork or stress.",
    translation: "quemarse / agotarse",
    exampleSentence: "He burned out after months of working seventy-hour weeks.",
    synonyms: ["exhaust oneself"],
    phrasalVerbs: ["burn out"],
    collocations: ["risk of burning out"],
    pronunciationIPA: "/bɜːn aʊt/",
    category: "health",
    cefrLevel: "B2",
  },
  {
    word: "well-rounded",
    definition: "Having a wide range of skills, experiences or interests.",
    translation: "completo / polifacético",
    exampleSentence: "The programme aims to give students a well-rounded education.",
    synonyms: ["versatile", "balanced"],
    collocations: ["well-rounded education", "well-rounded individual"],
    pronunciationIPA: "/ˌwelˈraʊn.dɪd/",
    category: "education",
    cefrLevel: "C1",
  },
  {
    word: "to grasp",
    definition: "To understand something fully, especially something complex.",
    translation: "comprender / captar",
    exampleSentence: "It took a while for the class to grasp the concept.",
    synonyms: ["understand", "comprehend"],
    collocations: ["grasp a concept", "fully grasp"],
    pronunciationIPA: "/ɡrɑːsp/",
    category: "education",
    cefrLevel: "B2",
  },
  {
    word: "rigorous",
    definition: "Thorough, careful, and demanding high standards.",
    translation: "riguroso",
    exampleSentence: "The university is known for its rigorous admissions process.",
    synonyms: ["thorough", "strict"],
    antonyms: ["lax", "sloppy"],
    collocations: ["rigorous testing", "rigorous standards"],
    pronunciationIPA: "/ˈrɪɡ.ər.əs/",
    category: "education",
    cefrLevel: "C1",
  },

  // --- travel ---
  {
    word: "to set off",
    definition: "To begin a journey.",
    translation: "ponerse en marcha / partir",
    exampleSentence: "We set off before dawn to avoid the traffic.",
    synonyms: ["depart", "head out"],
    phrasalVerbs: ["set off"],
    collocations: ["set off early", "set off on a journey"],
    pronunciationIPA: "/set ɒf/",
    category: "travel",
    cefrLevel: "B1",
  },
  {
    word: "itinerary",
    definition: "A planned route or schedule for a journey.",
    translation: "itinerario",
    exampleSentence: "Our itinerary includes three days in the mountains.",
    synonyms: ["route", "schedule"],
    collocations: ["detailed itinerary", "travel itinerary"],
    pronunciationIPA: "/aɪˈtɪn.ər.ər.i/",
    category: "travel",
    cefrLevel: "B2",
  },
  {
    word: "off the beaten track",
    definition: "In a place that is not often visited by tourists.",
    translation: "fuera de los circuitos turísticos",
    exampleSentence: "We prefer destinations that are off the beaten track.",
    synonyms: ["remote", "unspoilt"],
    collocations: ["places off the beaten track"],
    pronunciationIPA: "/ɒf ðə ˈbiː.tən træk/",
    category: "travel",
    cefrLevel: "C1",
  },
];
